export const mock = [
  {
    id: "0",
    url: "#",
    image: "https://i.ytimg.com/vi/7lCDEYXw3mM/hqdefault.jpg",
    channelUrl: "#",
    channelName: "Name",
    title: "Title",
    date: "2012-06-20T22:45:24.000Z",
    description: "Description",
    viewCount: 0,
  },
  {
    id: "1",
    url: "#",
    image: "https://i.ytimg.com/vi/7lCDEYXw3mM/hqdefault.jpg",
    channelUrl: "#",
    channelName: "Name",
    title: "Title",
    date: "2013-06-20T22:45:24.000Z",
    description: "Description",
    viewCount: 1,
  },
  {
    id: "2",
    url: "#",
    image: "https://i.ytimg.com/vi/7lCDEYXw3mM/hqdefault.jpg",
    channelUrl: "#",
    channelName: "Name",
    title: "Title",
    date: "2014-06-20T22:45:24.000Z",
    description: "Description",
    viewCount: 2,
  },
  {
    id: "3",
    url: "#",
    image: "https://i.ytimg.com/vi/7lCDEYXw3mM/hqdefault.jpg",
    channelUrl: "#",
    channelName: "Name",
    title: "Title",
    date: "2015-06-20T22:45:24.000Z",
    description: "Description",
    viewCount: 3,
  },
  {
    id: "4",
    url: "#",
    image: "https://i.ytimg.com/vi/7lCDEYXw3mM/hqdefault.jpg",
    channelUrl: "#",
    channelName: "Name",
    title: "Title",
    date: "2015-06-20T22:45:24.000Z",
    description: "Description",
    viewCount: 4,
  }
];
